[tools]
usage = "latest"
go = "latest"
node = "24.3.0"
lua = "latest"
python = "3.14.1"
ruby = "latest"
rust = "latest"
pnpm = "latest"

[settings]
# configure `mise install` to always keep the downloaded archive
always_keep_download = true # deleted after install by default
always_keep_install = true  # deleted on failure by default
asdf_compat = false
