tap "solidiquis/tap"
brew "erdtree"
brew "libgit2"
brew "openssl@1.1"
brew "eza"
brew "fd"
brew "gitui"
brew "gnupg"
brew "pkgconf"
brew "graphviz"
brew "lazygit"
brew "mise"
brew "neofetch"
brew "neovim"
brew "pipes-sh", link: false
brew "pre-commit"
brew "ripgrep"
brew "stow"
brew "tmux"
brew "jq"

# ZSH stuff
brew "starship"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"
brew "zsh-history-substring-search"
brew "fzf"

# Fonts
cask "font-jetbrains-mono-nerd-font"
cask "font-0xproto-nerd-font"

cask "caffeine"
cask "ghostty"
cask "linearmouse"

# Sketchy bar
tap "FelixKratz/formulae"
brew "sketchybar", restart_service: :changed

# Window manager
cask "nikitabobko/tap/aerospace"

vscode "amazonwebservices.aws-toolkit-vscode"
vscode "anseki.vscode-color"
vscode "arcanis.vscode-zipfs"
vscode "asvetliakov.vscode-neovim"
vscode "bradlc.vscode-tailwindcss"
vscode "christian-kohler.path-intellisense"
vscode "daltonmenezes.aura-theme"
vscode "dbaeumer.vscode-eslint"
vscode "docker.docker"
vscode "dracula-theme.theme-dracula"
vscode "dsznajder.es7-react-js-snippets"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.auto-rename-tag"
vscode "github.github-vscode-theme"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "graphql.vscode-graphql"
vscode "graphql.vscode-graphql-execution"
vscode "graphql.vscode-graphql-syntax"
vscode "hbenl.vscode-mocha-test-adapter"
vscode "hbenl.vscode-test-explorer"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-vscode.live-server"
vscode "ms-vscode.test-adapter-converter"
vscode "orta.vscode-jest"
vscode "pkief.material-icon-theme"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "ryanluker.vscode-coverage-gutters"
vscode "teabyii.ayu"
vscode "unifiedjs.vscode-mdx"
vscode "vitest.explorer"
vscode "wenfangdu.snippet-generator"
vscode "zxh404.vscode-proto3"
