# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# ==== Theme ====

add_newline = false
# palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
separator = "#585b70"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# ==== Format ====

# Use custom format
format = '''
[┌───────────────────>]
[│]$directory$rust$package
[└─>] '''


# [directory]
# style = "bold mauve"
# format = "[$path]($style)"
# truncation_length = 3
# truncate_to_repo = false

# format = """
# [╭](fg:separator)\
# $status\
# $directory\
# $cmd_duration\
# $line_break\
# [╰](fg:separator)\
# $character\
# """

# ==== Prompt Components ====

# [directory]
# read_only = " 󰌾"
# truncation_length = 0
# truncate_to_repo = false
# format = "[─](fg:separator)[](fg:teal bg:surface1)[](fg:base bg:teal)[](fg:teal bg:surface1)[ $path](bg:surface1)[](fg:surface1)"
# home_symbol = "~"

# [status]
# format = "[─](fg:separator)[](fg:status)[](fg:icon bg:status)[](fg:status bg:background)[ $status](bg:background)[](fg:background)"
# pipestatus = true
# pipestatus_separator = "-"
# pipestatus_segment_format = "$status"
# pipestatus_format = "[─](fg:separator)[](fg:status)[](fg:icon bg:status)[](fg:status bg:background)[ $pipestatus](bg:background)[](fg:background)"
# disabled = false

# [cmd_duration]
# format = "[─](fg:separator)[](fg:duration)[󱐋](fg:icon bg:duration)[](fg:duration bg:background)[ $duration](bg:background)[](fg:background)"
# min_time = 1000

# [time]
# format = "[](fg:duration)[󰥔](fg:icon bg:duration)[](fg:duration bg:background)[ $time](bg:background)[](fg:background)"
# disabled = true

# [character]
# success_symbol = "[❯](bold green)"
# error_symbol = "[❯](bold red)"
# vimcmd_symbol = "[❮](bold green)"
